Resources:
  ApiGatewayAuthorizer: 
    Type: AWS::ApiGateway::Authorizer
    Properties: 
      Name: ${ self:custom.serviceStage }
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: 
        Ref: ApiGatewayRestApi
      ProviderARNs: 
        - Fn::GetAtt:
            - CognitoUserPool
            - Arn